server:
  port: 9001
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /client-one


eureka:
  client:
    service-url:
          #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
          defaultZone: http://node2.com:8762/eureka/,http://node3.com:8763/eureka/,http://node4.com:8764/eureka/ #集群版

spring:
  application:
    name: client-one
