server:
  port: 8764
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /eureka


#是否将自己注册到Eureka-Server中，默认的为true
eureka:
  instance:
    hostname: node4
  client:

    register-with-eureka: false
    fetch-registry: false
    service-url:
          #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
          defaultZone: http://node2.com:8762/eureka/,http://node3.com:8763/eureka/ #集群版

spring:
  application:
    name: eureka-server
